app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      #URL para banco da aplicaçao
      #jdbc-url: jdbc:postgresql://localhost:5432/postgres
      #URL para banco de testes
      jdbc-url: ${teste.datasource.url}
      password: 'postgres'
      pool-size: 30
      username: postgres

server:
  error:
    include-binding-errors: always
    include-message: always

